#!/usr/bin/python

#import OpenSSL.crypto
import rfc3161

#sudo apt-get install python-pyasn1 python-pyasn1-modules python-m2crypto

#with open("cert.der") as f:
#	der = f.read()
#x509 = OpenSSL.crypto.load_certificate(der)
aruba_tsa_server = "https://servizi.arubapec.it/tsa/ngrequest.php"
username = "TSA100288"
password = "WJVMhoVv"
carta_pin = "12345678"

kwargs = {"username": username, "password": password}

timestamper = rfc3161.RemoteTimestamper(aruba_tsa_server, **kwargs)



